---
title: "main.Rmd"
author: "Dominic Munns"
date: "04/11/2020"
output: 
  bookdown::pdf_document2: default
  bookdown::word_document2: default
  bookdwon::html_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
# default code
```
```{r packages}
library(tidyverse)
# code for package loading

```
#Introduction
This is my introduction.

#Methods
Some interesting techniques.

#Results


#Discussion

```{r import}
#import dataset
chaff <- read.table("raw_data/chaff.txt", header = TRUE)

```
```{r tidy}
#tidy data
library(tidyverse)
chaff2 <- gather(chaff, key = sex, mass)
```
```{r SS(x)}
sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff2, mass, sex)
```

```{r summary}
chaffsum <- chaff2 %>% 
  group_by(sex) %>% 
  summarise(mean_chaff = mean(mass),
            n = length(mass))
```

